language: node_js
node_js:
 - "0.11.15"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
 - sudo apt-get install build-essential
 - sudo apt-get install npm
 - sudo npm update
 - npm config set registry http://registry.npmjs.org/
 - sudo npm install -g node-gyp
 - sudo npm install -g mocha
script: 
  - node-gyp configure build --target=v0.11.15 --debug
  - ./test/nodejs/test.sh
os: linux
notifications:
  email:  
  - jan.rupnik@ijs.si
