language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
install:
  - make lib
script: 
  - make
  - make test
  - ./test/javascript/test.sh
os: linux
notifications:
  email:
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
