language: node_js
node_js:
  - "0.12.3"
env:  
  - CXXFLAGS=-std=c++0x CXX=g++ CC=gcc  
  - CXXFLAGS=-std=c++0x CXX=clang++-3.6 CC=clang NPMOPT=--clang=1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install build-essential
  - if [ "$CXX" = "clang++-3.6" ]; then sudo apt-get install clang-3.6; fi
  - npm install -g mocha
install:
  - npm install $NPMOPT
script:   
  - ./test/nodejs/test.sh
os: linux
notifications:
  email:  
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
  - viktor@carvic.si
