language: node_js
node_js:
  - "0.12.3"
env:  
  - CXXFLAGS=-std=c++0x CXX=g++ CC=gcc  
  - CXXFLAGS=-std=c++0x CXX=clang++-3.5 CC=clang NPMOPT=--clang=1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install build-essential

  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update
  - apt-cache search clang

  - if [ "$CXX" = "clang++-3.5" ]; then sudo apt-get install -y clang-3.5; fi
  - npm install -g mocha
install:
  - npm install $NPMOPT
script:   
  - ./test/nodejs/test.sh
os: linux
notifications:
  email:  
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
  - viktor@carvic.si
