language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
 - sudo apt-get install npm
 - sudo npm update
 - npm config set registry http://registry.npmjs.org/
 - sudo npm install -g node-gyp
 - ./test/cpp/install.sh
install:
  - ./configure
  - make lib
script: 
  - node-gyp --nodedir=src/third_party/node configure build
  - make
  - make test
  - ./test/javascript/test.sh
os: linux
notifications:
  email:
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
