language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq uuid-dev
install:
  - make lib
script: 
  - make
  - ./test/javascript/test.sh
os: linux
notifications:
  email:
    - mario.karlovcec@ijs.si
    - mario.karlovcec@gmail.si
