language: node_js
node_js:
  - "0.11.14"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install build-essential
  - npm install -g mocha
  - npm install --debug
script:   
  - ./test/nodejs/test.sh
os: linux
notifications:
  email:  
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
