language: node_js
node_js:
  - "0.11"
before_install:
 - sudo apt-get install build-essential
 - sudo apt-get install npm
 - sudo npm update
 - npm config set registry http://registry.npmjs.org/
 - sudo npm install -g node-gyp
script: 
  - node-gyp configure build --target=v0.11.14
os: linux
notifications:
  email:  
  - jan.rupnik@ijs.si
