environment:
  node_pre_gyp_accessKeyId:
    secure: jxPeHdKaFnYcMFAUkX+/lcUCKEha3yp5pxxMACxx/lM=
  node_pre_gyp_secretAccessKey:
    secure: 7nDsFrQjWQfhXAPESzf6JO+mslguRKGAPyZ5C4x6Sklcuv4E8/3gkGqoahJJKbZo
  matrix:
    - nodejs_version: 0.12.7

platform:
  - x64

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm update -g npm
  - npm --version
  - node -e "console.log(process.arch);"
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - npm install -g mustache
  - npm install --build-from-source --verbose
  - cd tools
  - genExampleTests.bat
  - cd ..
  - cd test\nodejs
  - npm install -g mocha
  - mocha --timeout 30000 *.js
  - cd ..\..
  - node_modules\.bin\node-pre-gyp package
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node_modules\.bin\node-pre-gyp publish



build: off
test: off
deploy: off
